/* eslint-disable max-lines */
// Ethnicities will cover those who have at least 20% of the population as of today
// based on wikipedia
// The code is based on this appendix: https://www.behindthename.com/api/appendix2.php
// If an ethnicity is not available on the site above, they are not added
// https://en.wikipedia.org/wiki/Indigenous_peoples_of_the_Americas
const countries = [
  {
    country: "Afghanistan",
    population: 37172386,
    code: "AF",
    ethnicities: ["pas", "taj"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Albania",
    population: 2866376,
    code: "AL",
    ethnicities: ["alb"],
    region: ["europe", "balkans"],
  },
  {
    country: "Algeria",
    population: 42228429,
    code: "DZ",
    ethnicities: ["ara", "ber"],
    region: ["africa", "north_africa"],
  },
  {
    country: "American Samoa",
    population: 55465,
    code: "AS",
    ethnicities: ["smn"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Andorra",
    population: 77006,
    code: "AD",
    ethnicities: ["cat", "spa", "por"],
    region: ["europe", "iberia"],
  },
  {
    country: "Angola",
    population: 30809762,
    code: "AO",
    ethnicities: ["kon", "mbu", "por"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Anguilla",
    population: 15094,
    code: "AI",
    ethnicities: ["eng"],
    region: ["caribbean", "central_america"],
  },
  // {
  //   country: "Antarctica",
  //   population: 1106,
  //   code: "AQ",
  //   ethnicities: ["eng"],
  //   region: ["antarctica"],
  // },
  {
    country: "Antigua and Barbuda",
    population: 96286,
    code: "AG",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Argentina",
    population: 44494502,
    code: "AR",
    ethnicities: ["spa", "map"],
    region: ["south_america", "latin"],
  },
  {
    country: "Armenia",
    population: 2951776,
    code: "AM",
    ethnicities: ["arm"],
    region: ["asia", "caucasus"],
  },
  {
    country: "Aruba",
    population: 105845,
    code: "AW",
    ethnicities: ["dut"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Australia",
    population: 24982688,
    code: "AU",
    ethnicities: ["eng"],
    region: ["oceania"],
  },
  {
    country: "Austria",
    population: 8840521,
    code: "AT",
    ethnicities: ["ger"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Azerbaijan",
    population: 9939800,
    code: "AZ",
    ethnicities: ["aze"],
    region: ["asia", "caucasus"],
  },
  {
    country: "Bahamas",
    population: 385640,
    code: "BS",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Bahrain",
    population: 1569439,
    code: "BH",
    ethnicities: ["ara", "per"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Bangladesh",
    population: 161356039,
    code: "BD",
    ethnicities: ["ben"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Barbados",
    population: 286641,
    code: "BB",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Belarus",
    population: 9483499,
    code: "BY",
    ethnicities: ["bel"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Belgium",
    population: 11433256,
    code: "BE",
    ethnicities: ["dut", "fre"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Belize",
    population: 383071,
    code: "BZ",
    ethnicities: ["may", "eng", "spa"],
    region: ["central_america", "latin"],
  },
  {
    country: "Benin",
    population: 11485048,
    code: "BJ",
    ethnicities: ["yor", "fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Bermuda",
    population: 63973,
    code: "BM",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Bhutan",
    population: 754394,
    code: "BT",
    ethnicities: ["bhu"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Bolivia",
    population: 11353142,
    code: "BO",
    ethnicities: ["aym", "que", "ame"],
    region: ["south_america", "latin"],
  },
  {
    country: "Bosnia and Herzegovina",
    population: 3323929,
    code: "BA",
    ethnicities: ["bos"],
    region: ["europe", "balkans"],
  },
  {
    country: "Botswana",
    population: 2254126,
    code: "BW",
    ethnicities: ["tsw"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Brazil",
    population: 209469333,
    code: "BR",
    ethnicities: ["por"],
    region: ["south_america", "latin"],
  },
  {
    country: "Brunei",
    population: 428962,
    code: "BN",
    ethnicities: ["mly"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Bulgaria",
    population: 7025037,
    code: "BG",
    ethnicities: ["bul"],
    region: ["europe", "balkans"],
  },
  {
    country: "Burkina Faso",
    population: 19751535,
    code: "BF",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Burundi",
    population: 11175378,
    code: "BI",
    ethnicities: ["swa"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Cambodia",
    population: 16249798,
    code: "KH",
    ethnicities: ["khm"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Cameroon",
    population: 25216237,
    code: "CM",
    ethnicities: ["eng", "fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Canada",
    population: 37057765,
    code: "CA",
    ethnicities: ["eng", "fre", "ame"],
    region: ["north_america", "canada"],
  },
  {
    country: "Cape Verde",
    population: 543767,
    code: "CV",
    ethnicities: ["por"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Cayman Islands",
    population: 64174,
    code: "KY",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Central African Republic",
    population: 4666377,
    code: "CF",
    ethnicities: ["afr", "fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Chad",
    population: 15477751,
    code: "TD",
    ethnicities: ["ara"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Chile",
    population: 18729160,
    code: "CL",
    ethnicities: ["map", "spa", "ame"],
    region: ["south_america", "latin"],
  },
  {
    country: "China",
    population: 1392730000,
    code: "CN",
    ethnicities: ["chi"],
    region: ["asia", "east_asia"],
  },
  {
    country: "Christmas Island",
    population: 1402,
    code: "CX",
    ethnicities: ["chi", "eng", "mly"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Cocos (Keeling) Islands",
    population: 596,
    code: "CC",
    ethnicities: ["mly"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Colombia",
    population: 49648685,
    code: "CO",
    ethnicities: ["spa", "ame"],
    region: ["south_america", "latin"],
  },
  {
    country: "Comoros",
    population: 832322,
    code: "KM",
    ethnicities: ["cmr"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Congo, The Republic of",
    population: 5244363,
    code: "CG",
    ethnicities: ["kon"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Congo, The Democratic Republic of",
    population: 84068091,
    code: "CD",
    ethnicities: ["kon"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Cook Islands",
    population: 17379,
    code: "CK",
    ethnicities: ["mao"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Costa Rica",
    population: 4999441,
    code: "CR",
    ethnicities: ["mao"],
    region: ["central_america", "latin"],
  },
  {
    country: "Croatia",
    population: 4087843,
    code: "HR",
    ethnicities: ["cro"],
    region: ["europe", "balkans"],
  },
  {
    country: "Cuba",
    population: 11338138,
    code: "CU",
    ethnicities: ["spa"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Cyprus",
    population: 1189265,
    code: "CY",
    ethnicities: ["gre", "tur"],
    region: ["asia", "mediterranean", "middle_east"],
  },
  {
    country: "Czech Republic",
    population: 10629928,
    code: "CZ",
    ethnicities: ["cze"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Denmark",
    population: 5793636,
    code: "DK",
    ethnicities: ["dan"],
    region: ["europe", "nordic"],
  },
  {
    country: "Djibouti",
    population: 958920,
    code: "DJ",
    ethnicities: ["som"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Dominica",
    population: 71625,
    code: "DM",
    ethnicities: ["fre"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Dominican Republic",
    population: 10627165,
    code: "DO",
    ethnicities: ["spa"],
    region: ["caribbean", "indies"],
  },
  {
    country: "East Timor",
    population: 1267972,
    code: "TP",
    ethnicities: ["por"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Ecuador",
    population: 17084357,
    code: "EC",
    ethnicities: ["spa", "ame"],
    region: ["south_america", "latin"],
  },
  {
    country: "Egypt",
    population: 98423595,
    code: "EG",
    ethnicities: ["ara"],
    region: ["africa", "middle_east"],
  },
  {
    country: "El Salvador",
    population: 6420744,
    code: "SV",
    ethnicities: ["spa"],
    region: ["central_america", "latin"],
  },
  {
    country: "Equatorial Guinea",
    population: 1308974,
    code: "GQ",
    ethnicities: ["spa"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Eritrea",
    population: 6213972,
    code: "ER",
    ethnicities: ["ara"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Estonia",
    population: 1321977,
    code: "EE",
    ethnicities: ["est"],
    region: ["europe", "baltic"],
  },
  {
    country: "Eswatini",
    population: 1136191,
    code: "SZ",
    ethnicities: ["zul"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Ethiopia",
    population: 109224559,
    code: "ET",
    ethnicities: ["eth", "oro", "amh"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Falkland Islands",
    population: 2840,
    code: "FK",
    ethnicities: ["eng"],
    region: ["south_america", "latin"],
  },
  {
    country: "Faroe Islands",
    population: 48497,
    code: "FO",
    ethnicities: ["fae"],
    region: ["europe", "nordic"],
  },
  {
    country: "Fiji Islands",
    population: 883483,
    code: "FJ",
    ethnicities: ["fij"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Finland",
    population: 5515525,
    code: "FI",
    ethnicities: ["fin"],
    region: ["europe", "nordic"],
  },
  {
    country: "France",
    population: 66977107,
    code: "FR",
    ethnicities: ["fre"],
    region: ["europe", "western_europe"],
  },
  {
    country: "French Guiana",
    population: 290691,
    code: "GF",
    ethnicities: ["fre"],
    region: ["south_america", "latin"],
  },
  {
    country: "French Polynesia",
    population: 277679,
    code: "PF",
    ethnicities: ["fre"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Gabon",
    population: 2119275,
    code: "GA",
    ethnicities: ["fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Gambia",
    population: 2280102,
    code: "GM",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Georgia",
    population: 3726549,
    code: "GE",
    ethnicities: ["geo"],
    region: ["asia", "caucasus"],
  },
  {
    country: "Germany",
    population: 82905782,
    code: "DE",
    ethnicities: ["ger"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Ghana",
    population: 29767108,
    code: "GH",
    ethnicities: ["aka", "ewe", "gaa"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Gibraltar",
    population: 33718,
    code: "GI",
    ethnicities: ["eng", "spa"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Greece",
    population: 10731726,
    code: "GR",
    ethnicities: ["gre"],
    region: ["europe", "mediterranean"],
  },
  {
    country: "Greenland",
    population: 56025,
    code: "GL",
    ethnicities: ["grn"],
    region: ["north_america", "nordic"],
  },
  {
    country: "Grenada",
    population: 111454,
    code: "GD",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Guadeloupe",
    population: 395700,
    code: "GP",
    ethnicities: ["fre"],
  },
  {
    country: "Guam",
    population: 165768,
    code: "GU",
    ethnicities: ["cha"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Guatemala",
    population: 17247807,
    code: "GT",
    ethnicities: ["may", "spa", "ame"],
    region: ["central_america", "latin"],
  },
  // {
  //   country: "Guernsey",
  //   population: 62999,
  //   code: "GG",
  //   ethnicities: ["eng", "fre"],
  //   region: ["europe", "western_europe"],
  // },
  {
    country: "Guinea",
    population: 12414318,
    code: "GN",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Guinea-Bissau",
    population: 1874309,
    code: "GW",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Guyana",
    population: 779004,
    code: "GY",
    ethnicities: ["eng", "hin", "afr", "ame"],
    region: ["south_america", "latin"],
  },
  {
    country: "Haiti",
    population: 11123176,
    code: "HT",
    ethnicities: ["fre"],
    region: ["caribbean", "indies"],
  },
  // {
  //   country: "Holy See (Vatican City State)",
  //   population: 825,
  //   code: "VA",
  // },
  {
    country: "Honduras",
    population: 9587522,
    code: "HN",
    ethnicities: ["spa"],
    region: ["central_america", "latin"],
  },
  {
    country: "Hong Kong",
    population: 7451000,
    code: "HK",
    ethnicities: ["chi"],
    region: ["asia", "east_asia"],
  },
  {
    country: "Hungary",
    population: 9775564,
    code: "HU",
    ethnicities: ["hun"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Iceland",
    population: 352721,
    code: "IS",
    ethnicities: ["ice"],
    region: ["europe", "nordic"],
  },
  {
    country: "India",
    population: 1352617328,
    code: "IN",
    ethnicities: ["ind"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Indonesia",
    population: 267663435,
    code: "ID",
    ethnicities: ["ins"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Iran",
    population: 81800269,
    code: "IR",
    ethnicities: ["per"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Iraq",
    population: 38433600,
    code: "IQ",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Ireland",
    population: 4867309,
    code: "IE",
    ethnicities: ["iri"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Israel",
    population: 8882800,
    code: "IL",
    ethnicities: ["heb"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Italy",
    population: 60421760,
    code: "IT",
    ethnicities: ["ita"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Ivory Coast",
    population: 25069229,
    code: "CI",
    ethnicities: ["aka"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Jamaica",
    population: 2934855,
    code: "JM",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Japan",
    population: 126529100,
    code: "JP",
    ethnicities: ["jap"],
    region: ["asia", "east_asia"],
  },
  // {
  //   country: "Jersey",
  //   population: 100800,
  //   code: "JE",
  // },
  {
    country: "Jordan",
    population: 9956011,
    code: "JO",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Kazakhstan",
    population: 18272430,
    code: "KZ",
    ethnicities: ["kaz"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Kenya",
    population: 51393010,
    code: "KE",
    ethnicities: ["kik", "luh", "luo"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Kiribati",
    population: 115847,
    code: "KI",
    ethnicities: ["mly"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Kuwait",
    population: 4137309,
    code: "KW",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Kyrgyzstan",
    population: 6322800,
    code: "KG",
    ethnicities: ["kyr"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Laos",
    population: 7061507,
    code: "LA",
    ethnicities: ["lao"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Latvia",
    population: 1927174,
    code: "LV",
    ethnicities: ["lat"],
    region: ["europe", "baltic"],
  },
  {
    country: "Lebanon",
    population: 6848925,
    code: "LB",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Lesotho",
    population: 2108132,
    code: "LS",
    ethnicities: ["sot"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Liberia",
    population: 4818977,
    code: "LR",
    ethnicities: ["eng"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Libya",
    population: 6678567,
    code: "LY",
    ethnicities: ["ara"],
    region: ["africa", "north_africa"],
  },
  {
    country: "Liechtenstein",
    population: 37910,
    code: "LI",
    ethnicities: ["ger"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Lithuania",
    population: 2801543,
    code: "LT",
    ethnicities: ["lth"],
    region: ["europe", "baltic"],
  },
  {
    country: "Luxembourg",
    population: 607950,
    code: "LU",
    ethnicities: ["fre", "por", "ger"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Macao",
    population: 631636,
    code: "MO",
    ethnicities: ["chi"],
    region: ["asia", "east_asia"],
  },
  {
    country: "North Macedonia",
    population: 2084367,
    code: "MK",
    ethnicities: ["mac"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Madagascar",
    population: 26262368,
    code: "MG",
    ethnicities: ["mly"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Malawi",
    population: 18143315,
    code: "MW",
    ethnicities: ["yao", "cew", "tum"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Malaysia",
    population: 31528585,
    code: "MY",
    ethnicities: ["mly"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Maldives",
    population: 515696,
    code: "MV",
    ethnicities: ["dhi"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Mali",
    population: 19077690,
    code: "ML",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Malta",
    population: 484630,
    code: "MT",
    ethnicities: ["mal"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Marshall Islands",
    population: 58413,
    code: "MH",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Martinique",
    population: 376480,
    code: "MQ",
    ethnicities: ["fre"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Mauritania",
    population: 4403319,
    code: "MR",
    ethnicities: ["ara", "ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Mauritius",
    population: 1265303,
    code: "MU",
    ethnicities: ["ind", "eng"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Mayotte",
    population: 270372,
    code: "YT",
    ethnicities: ["fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Mexico",
    population: 126190788,
    code: "MX",
    ethnicities: ["may", "nah", "zap", "spa"],
    region: ["north_america", "latin"],
  },
  {
    country: "Micronesia, Federated States of",
    population: 112640,
    code: "FM",
    ethnicities: ["cha"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Moldova",
    population: 2706049,
    code: "MD",
    ethnicities: ["rmn"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Monaco",
    population: 38682,
    code: "MC",
    ethnicities: ["fre"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Mongolia",
    population: 3170208,
    code: "MN",
    ethnicities: ["mon"],
    region: ["asia", "east_asia"],
  },
  {
    country: "Montenegro",
    population: 631219,
    code: "ME",
    ethnicities: ["ser"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Montserrat",
    population: 5900,
    code: "MS",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Morocco",
    population: 36029138,
    code: "MA",
    ethnicities: ["ara", "ber"],
    region: ["africa", "north_africa"],
  },
  {
    country: "Mozambique",
    population: 29495962,
    code: "MZ",
    ethnicities: ["cew", "yao"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Myanmar",
    population: 53708395,
    code: "MM",
    ethnicities: ["bur"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Namibia",
    population: 2448255,
    code: "NA",
    ethnicities: ["afk"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Nauru",
    population: 12704,
    code: "NR",
    ethnicities: ["cha"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Nepal",
    population: 28087871,
    code: "NP",
    ethnicities: ["nep"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Netherlands",
    population: 17231624,
    code: "NL",
    ethnicities: ["dut"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Netherlands Antilles",
    population: 227049,
    code: "AN",
    ethnicities: ["dut", "eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "New Caledonia",
    population: 284060,
    code: "NC",
    ethnicities: ["fre"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "New Zealand",
    population: 4841000,
    code: "NZ",
    ethnicities: ["eng", "mao"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Nicaragua",
    population: 6465513,
    code: "NI",
    ethnicities: ["spa"],
    region: ["central_america", "latin"],
  },
  {
    country: "Niger",
    population: 22442948,
    code: "NE",
    ethnicities: ["hau", "ber"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Nigeria",
    population: 195874740,
    code: "NG",
    ethnicities: ["yor", "hau", "igb", "ibi", "urh"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Niue",
    population: 1624,
    code: "NU",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Norfolk Island",
    population: 2169,
    code: "NF",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "North Korea",
    population: 25549819,
    code: "KP",
    ethnicities: ["kor"],
    region: ["asia", "east_asia"],
  },
  {
    country: "Northern Mariana Islands",
    population: 56882,
    code: "MP",
    ethnicities: ["fil", "cha"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Norway",
    population: 5311916,
    code: "NO",
    ethnicities: ["nor"],
    region: ["europe", "northern_europe"],
  },
  {
    country: "Oman",
    population: 4829483,
    code: "OM",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Pakistan",
    population: 212215030,
    code: "PK",
    ethnicities: ["urd", "pun", "pas"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Palau",
    population: 17907,
    code: "PW",
    ethnicities: ["mly"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Palestine",
    population: 4569087,
    code: "PS",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Panama",
    population: 4176873,
    code: "PA",
    ethnicities: ["spa"],
    region: ["central_america", "latin"],
  },
  {
    country: "Papua New Guinea",
    population: 8606316,
    code: "PG",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Paraguay",
    population: 6956071,
    code: "PY",
    ethnicities: ["spa", "gua"],
    region: ["south_america", "latin"],
  },
  {
    country: "Peru",
    population: 31989256,
    code: "PE",
    ethnicities: ["spa", "aym"],
    region: ["south_america", "latin"],
  },
  {
    country: "Philippines",
    population: 106651922,
    code: "PH",
    ethnicities: ["fil", "tag"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Pitcairn",
    population: 67,
    code: "PN",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Poland",
    population: 37974750,
    code: "PL",
    ethnicities: ["pol"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Portugal",
    population: 10283822,
    code: "PT",
    ethnicities: ["por"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Puerto Rico",
    population: 3195153,
    code: "PR",
    ethnicities: ["spa"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Qatar",
    population: 2781677,
    code: "QA",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Reunion",
    population: 859959,
    code: "RE",
    ethnicities: ["fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Romania",
    population: 19466145,
    code: "RO",
    ethnicities: ["rmn"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Russia",
    population: 144478050,
    code: "RU",
    ethnicities: ["rus"],
    region: ["europe", "eastern_europe"],
  },
  {
    country: "Rwanda",
    population: 12301939,
    code: "RW",
    ethnicities: ["kig"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Saint Helena",
    population: 6600,
    code: "SH",
    ethnicities: ["eng"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Saint Kitts and Nevis",
    population: 52441,
    code: "KN",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Saint Lucia",
    population: 181889,
    code: "LC",
    ethnicities: ["eng", "fre"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Saint Pierre and Miquelon",
    population: 5888,
    code: "PM",
    ethnicities: ["fre"],
    region: ["north_america"],
  },
  {
    country: "Saint Vincent and the Grenadines",
    population: 110210,
    code: "VC",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Samoa",
    population: 196130,
    code: "WS",
    ethnicities: ["smn"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "San Marino",
    population: 33785,
    code: "SM",
    ethnicities: ["ita"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Sao Tome and Principe",
    population: 211028,
    code: "ST",
    ethnicities: ["por"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Saudi Arabia",
    population: 33699947,
    code: "SA",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Senegal",
    population: 15854360,
    code: "SN",
    ethnicities: ["ful"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Serbia",
    population: 6963764,
    code: "RS",
    ethnicities: ["ser"],
    region: ["europe", "balkans"],
  },
  {
    country: "Seychelles",
    population: 96762,
    code: "SC",
    ethnicities: ["eng", "fre"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Sierra Leone",
    population: 7650154,
    code: "SL",
    ethnicities: ["eng"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Singapore",
    population: 5638676,
    code: "SG",
    ethnicities: ["chi", "mly"],
    region: ["asia", "south_asia"],
  },
  // {
  //   country: "Sint Maarten (Dutch part)",
  //   population: 40654,
  //   code: "SX",
  //   ethnicities: ["dut"],
  //   region: ["caribbean", "indies"],
  // },
  {
    country: "Slovakia",
    population: 5446771,
    code: "SK",
    ethnicities: ["slk"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Slovenia",
    population: 2073894,
    code: "SI",
    ethnicities: ["sln"],
    region: ["europe", "central_europe"],
  },
  {
    country: "Solomon Islands",
    population: 652858,
    code: "SB",
    ethnicities: ["eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Somalia",
    population: 15008154,
    code: "SO",
    ethnicities: ["som"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "South Africa",
    population: 57779622,
    code: "ZA",
    ethnicities: ["zul", "xho", "afk"],
    region: ["africa", "sub_sahara"],
  },
  // {
  //   country: "South Georgia and the South Sandwich Islands",
  //   population: 30,
  //   code: "GS",
  //   ethnicities: ["eng"],
  //   region: ["antarctica"],
  // },
  {
    country: "South Korea",
    population: 51606633,
    code: "KR",
    ethnicities: ["kor"],
    region: ["asia", "east_asia"],
  },
  {
    country: "South Sudan",
    population: 10975920,
    code: "SS",
    // No ethnicities found
    ethnicities: ["ara", "afr"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Spain",
    population: 46796540,
    code: "ES",
    ethnicities: ["spa"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Sri Lanka",
    population: 21670000,
    code: "LK",
    ethnicities: ["sin", "tam"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Sudan",
    population: 41801533,
    code: "SD",
    ethnicities: ["ara"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Suriname",
    population: 575991,
    code: "SR",
    ethnicities: ["hin", "jav", "dut"],
    region: ["south_america", "latin"],
  },
  {
    country: "Svalbard and Jan Mayen",
    population: 2572,
    code: "SJ",
    ethnicities: ["nor"],
    region: ["europe", "northern_europe"],
  },
  {
    country: "Sweden",
    population: 10175214,
    code: "SE",
    ethnicities: ["swe"],
    region: ["europe", "northern_europe"],
  },
  {
    country: "Switzerland",
    population: 8513227,
    code: "CH",
    ethnicities: ["ger", "fre", "ita"],
    region: ["europe", "western_europe"],
  },
  {
    country: "Syria",
    population: 16906283,
    code: "SY",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Tajikistan",
    population: 9100837,
    code: "TJ",
    ethnicities: ["taj"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Tanzania",
    population: 56318348,
    code: "TZ",
    ethnicities: ["swa", "mwe", "tum", "yao"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Thailand",
    population: 69428524,
    code: "TH",
    ethnicities: ["tha"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Togo",
    population: 7889094,
    code: "TG",
    ethnicities: ["ewe"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Tokelau",
    population: 1411,
    code: "TK",
    ethnicities: ["sam"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Tonga",
    population: 103197,
    code: "TO",
    ethnicities: ["ton"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Trinidad and Tobago",
    population: 1389858,
    code: "TT",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Tunisia",
    population: 11565204,
    code: "TN",
    ethnicities: ["ara"],
    region: ["africa", "north_africa"],
  },
  {
    country: "Turkey",
    population: 82319724,
    code: "TR",
    ethnicities: ["tur"],
    region: ["europe", "middle_east"],
  },
  {
    country: "Turkmenistan",
    population: 5850908,
    code: "TM",
    ethnicities: ["tkm"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Turks and Caicos Islands",
    population: 37665,
    code: "TC",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Tuvalu",
    population: 11508,
    code: "TV",
    ethnicities: ["ton"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Uganda",
    population: 42723139,
    code: "UG",
    ethnicities: ["gan", "kig"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Ukraine",
    population: 44622516,
    code: "UA",
    ethnicities: ["ukr"],
    region: ["europe", "eastern_europe"],
  },
  {
    country: "United Arab Emirates",
    population: 9630959,
    code: "AE",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "United Kingdom",
    population: 66460344,
    code: "UK",
    ethnicities: ["eng", "sco", "wel", "iri"],
    region: ["europe", "western_europe"],
  },
  {
    country: "United States",
    population: 326687501,
    code: "US",
    ethnicities: [
      "usa",
      "eng",
      "apa",
      "che",
      "chy",
      "com",
      "iro",
      "nav",
      "oji",
      "pow",
      "sio",
    ],
    region: ["north_america"],
  },
  {
    country: "United States Minor Outlying Islands",
    population: 300,
    code: "UM",
    ethnicities: ["usa", "eng"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Uruguay",
    population: 3449299,
    code: "UY",
    ethnicities: ["spa"],
    region: ["south_america", "latin"],
  },
  {
    country: "Uzbekistan",
    population: 32955400,
    code: "UZ",
    ethnicities: ["uzb"],
    region: ["asia", "central_asia"],
  },
  {
    country: "Vanuatu",
    population: 292680,
    code: "VU",
    ethnicities: ["eng", "fre"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Venezuela",
    population: 28870195,
    code: "VE",
    ethnicities: ["spa"],
    region: ["south_america", "latin"],
  },
  {
    country: "Vietnam",
    population: 95540395,
    code: "VN",
    ethnicities: ["vie"],
    region: ["asia", "south_asia"],
  },
  {
    country: "Virgin Islands, British",
    population: 29802,
    code: "VG",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Virgin Islands, U.S.",
    population: 106977,
    code: "VI",
    ethnicities: ["eng"],
    region: ["caribbean", "indies"],
  },
  {
    country: "Wallis and Futuna",
    population: 15289,
    code: "WF",
    ethnicities: ["fre"],
    region: ["oceania", "polynesia"],
  },
  {
    country: "Western Sahara",
    population: 652271,
    code: "EH",
    ethnicities: ["ara", "ber"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Yemen",
    population: 28498687,
    code: "YE",
    ethnicities: ["ara"],
    region: ["asia", "middle_east"],
  },
  {
    country: "Zambia",
    population: 17351822,
    code: "ZM",
    ethnicities: ["ton", "cew", "tum"],
    region: ["africa", "sub_sahara"],
  },
  {
    country: "Zimbabwe",
    population: 14439018,
    code: "ZW",
    ethnicities: ["nde", "sho"],
    region: ["africa", "sub_sahara"],
  },
];

export default countries;
