type FormatType =
  | "bold"
  | "italic"
  | "strike"
  | "code"
  | "clear-text"
  | "clear-all"
  | "paragraph"
  | "heading-1"
  | "heading-2"
  | "heading-3"
  | "heading-4"
  | "heading-5"
  | "heading-6"
  | "bulletList"
  | "orderedList"
  | "codeBlock"
  | "blockquote"
  | "hardBreak"
  | "horizontalRule"
  | "undo"
  | "redo"
  | "highlight"
  | "underline"
  | "superscript"
  | "subscript"
  | "color"
  | "taskList"
  | "link"
  | "align-left"
  | "align-center"
  | "align-justify"
  | "align-right";

export default FormatType;
